### ISSUE TITLE
update

### ISSUE THREAD

**Issue by nicolgit** [johnnyjr/FlicLib.Sharp#1]
Hi johnnyjr, I see that this lib is updated to 1 year ago. do you plan to update it with latest flic libraries?

thank you!

**Comment by johnnyjr** [comment]
Hi @nicolgit
I haven't actually used this myself for about a year, so that is why (and there hasn't been much demand for any work from anyone else either), but now that I obviously have at least one person interested in this repo I might just take a look at it :)

**Comment by nicolgit** [comment]
Thank you! :-)

I am one of the developers of Caledos Runner an app that we're releasing for Android, and this toy looks interesting for our fitness scenario...

https://www.facebook.com/caledosRunner/
